name: deploy on push
on:[push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      -name: check out the code to build server
       uses: actions/checkout@v3
      -name: copy file to server
       uses: appleboy/scp_action@master
       with: 
        host: ${{54.85.157.142}}
        username: ${{ubuntu}}
        port: ${{22}}
        key: ${{MIIEogIBAAKCAQEAgk370Fpuk5zRyUJCw+DsAgZIk/nzlLqvyrY6DDtHmesoyMXD
9YXE1ROzIm4B2yaNtL8CTVjS4MJIOzylCO4l8Ba4OEyJXb2u13cc+qDr3Nx9e/qc
FNYexBvZTP8Pg0GsKMCyycl3oNR9ez/mG4v31lT9t0mWLNKPasU07GsEmZ1O4fJf
EhcM4yriAB0Fy6kLheOmjuXIFGVzmCgn3QDc4saZhei8qPJHUKuGOxRSPQonrKHm
SwgQhrdBcD9hUkNVWVCK5Q9JAronV4BMfceLcHGa1X3NgdMtCDJg7DK8b4iJg7PA
/W7fElwpOXBeFcZgsR5wJQSk3Z3njf9ldfwBpwIDAQABAoIBAGnkjA6PXytQlt/y
nCVpBQLELnkq+HtWl4OqQVQtXIvGIne+1/gQRJxQjRQeyB1boG9RhsJqu7zxxhd1
ujyepHAPVphSApQOkScC4qb+3Y64FLYLPIpmU8xVQWukH+wwE4NuzhzUQAaQiIT/
sbWTMs6YdTNddtBoMSq4psC2W5+loHu3aeqcPxBLQ4B1LoOU2ov+6wnCCt8WKEsO
2yDq9DkHSfotrlGPMgEQ0x4IaooF5hT6W3qjg52ms8hnNGgVPD2Hqzy3vOVW+5xT
IzWl6mvgEp++2SkzvjGrNlreR3xX/q5d7gN+2N/legkmXusLcaydugVMrXnssHOZ
KcoyFtECgYEAxSVIkK3+iDBUkoyiTSiDwh0VPq92V4krYV/kmIBKLZjOoB/q63xF
dy4Uh8sA27flxRXB87hEPZAmUtHXZhM6La61mf7l4rvr2JBwU7nvffB5XIGVTfvz
pIbjGVukRrlK3ZSKK6d2y/Od9CCeHpSI2IOTnULDxukICJRImJgG468CgYEAqTRs
NwXq1kjvM08oG89sVrmEpFjxh6idZ5N8FzhE0XIHr/Hqh7ySG+5Cll5e0dSyGbwc
NPpVvWUKsrjUI0yQQ9DKQ5soeUM+pTSTGwTCAQq7X7OZApxqxFi3FIHtOOFOfrTN
JhBA2x+O9nK/dBt8UEfPGFXu0Bv2C+NK6/DLp4kCgYAh49Dfnil9O+Gt96MG5IoR
2nIGfp83WQsuCBAB7zvRLs2GVTZLGOfQHwnEdi9Flg1Xne/jd6+zbY5I+m2uzGtZ
4wiw2lKmcWuPpPTKT9JNsgMK1fPWnhM6Gz364/gPeFbYVGqUKouPb+edSeYkl6AW
qDe99vY0wWZyIxt/r9KvXQKBgFVPpBwd9Khz/36cM3nKHDKhuPnwCl8+qZY2a0N9
0FzVpICWdYxYjEZe293a2O3s0ptdF8+yRBaI4lr4C6V8jeRTWhe6HC7/s48yMdVW
kcZatdxrvgLuAHrcy/ogBA5AswX5fNHrMfgJMliZxGPzE7uaaRU5Bn6RCn417GmH
b/cZAoGAOJWV5JnQwCoT1qhY+Yw+xWuMKlK+3YfKkRrno/XBW1wZ+mgVOiVYoghk
Y6cdDu9xpBtPLR486Mvsk5KtqRKJTLuNAnW6nFwh3ITwVLLuEo5uX4hKsvXe89c7
nPp2bIZFULDtrRdvSB7PHt6QRbyVwjMFfQxKdXIs7HuIk90a4Rs=}}
        source: "./html/*"
        target: "/var/www/html"
        strip_components: 1